# Random Forest Classifier

## ToDo: Fill this in

In [83]:
from collections import namedtuple

import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [89]:
ForestTree = namedtuple('ForestTree', ['tree', 'feature_inds'])

class RandomForestClassifier:
    
    def __init__(self, n_estimators, n_features, n_samples):
        self.n_estimators = n_estimators
        self.trees = []
        self.n_features = n_features
        self.n_samples = n_samples
    
    def fit(self, X, y):
        for i in range(self.n_estimators):         
            # Randomly subsample observation-wise and feature-wise
            sample_inds = np.random.choice(X.shape[0], size=self.n_samples, replace=False)
            sample_feats = np.random.choice(X.shape[1], size=self.n_features, replace=False)
            X_sample = X[sample_inds,:][:, sample_feats]  # X[sample_inds, sample_feats] returns a 1d array here.
            y_sample = y[sample_inds]
    
            # Fit the Decision Tree on the subsampled data
            tree = DecisionTreeClassifier()
            tree.fit(X_sample, y_sample)
            self.trees.append(ForestTree(tree, sample_feats))
            
    def predict(self, X):
        all_tree_predictions = np.array([t.tree.predict(X[:, t.feature_inds]) for t in self.trees])
        forest_predictions = np.squeeze(mode(all_tree_predictions, axis=0).mode)
        return forest_predictions

In [90]:
iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [91]:
clf = RandomForestClassifier(n_estimators=100, n_features=2, n_samples=30)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

In [95]:
print('Accuracy score: {}'.format(accuracy_score(y_pred, y_test)))
print('Confusion matrix:')
print(confusion_matrix(y_pred, y_test))
      

Accuracy score: 0.9666666666666667
Confusion matrix:
[[ 8  0  0]
 [ 0 10  1]
 [ 0  0 11]]
